### ISSUE TITLE
error when accessing http://localhost/sqli-labs/sql-connections/setup-db.php

### ISSUE THREAD

**Issue by januspatrick** [Audi-1/sqli-labs#5]
EX of Code error:  

```
                                          Welcome    Dhakkan
```

SETTING UP THE DATABASE SCHEMA AND POPULATING DATA IN TABLES:

";} else {echo "[*]...................Error purging database: " . mysql_error(); echo "

";} //Creating new database security $sql="CREATE database `security` CHARACTER S, ET `gbk` "; if (mysql_query($sql)) {echo "[*]...................Creating New database successfully";echo "

";} else {echo "[*]...................Error creating database: " . mysql_error();echo "
## blah, blah, blah, blah

Ive tried to reinstall this twice with the same error when clicking on the  Setup/reset Database.   Im using current version of Ubuntu.  Apache2 has been installed and works.  Same with mysql.  

File location:
/var/www/sqli-labs/

Any suggestions?

**Comment by Audi-1** [comment]
This issue seems to be unique to you because i tested it and it works fine. May be it is being affected because of the way how you copy it. Did u try cloning the repo using Git commands. 
Generally this happens when the code in the file is not getting interpreted as intended. I am not a programer by heart but saw some issues with unbalanced HTML TAGS. updated the file, so you should not have any issue. 
Else you can copy the SQL strings manually and paste them into mysql editor to get the database populated manually line by line.

**Comment by a0xnirudh** [comment]
@januspatrick  The above mentioned issue seems to exist on normal Ubuntu versions because I personally tried it on 2 different machines and end up with the above error state. Since the sqli-labs are optimized to work with Kali linux, it will be best if users can install Kali in virtual box and then you can do the same in kali after you start apache2 and mysql services (You have to do this manually since they will not be started by default when kali boots up.). After that if you don't like to work on virtual box (like me), you can set a host only adapter in virtual box configuration which will assign a particular ip address to your kali machine, something like 192.168.xx.xx.

Once this is done, you can access the sqli-labs from the host machine by going to 192.168.xx.xx/sqli-labs . 

Here is an old tutorial I have written about setting up host only adapter in virtual box:  http://goo.gl/wYrMS2

@Audi-1 I am not sure why it happens in Ubuntu varients (I am still not sure if it happens on every ubuntu varients but its happening for me and my friends machine) but I will take a detail look into it and will try to fix it. 

Sqli-labs is an extremly wonderful job from your side ..

**Comment by ankii0126** [comment]
hiii i am also facing this same issue
and I am using kali 
please reply if you had solved this issue.

SETTING UP THE DATABASE SCHEMA AND POPULATING DATA IN TABLES:


\n";} else {echo "[*]...................Error purging database: " . mysql_error(); echo "

\n";} //Creating new database security $sql="CREATE database `security` CHARACTER SET `gbk` "; if (mysql_query($sql)) {echo "[*]...................Creating New database 'SECURITY' successfully";echo "

\n";} else {echo "[*]...................Error creating database: " . mysql_error();echo "

\n";} //creating table users $sql="CREATE TABLE security.users (id int(3) NOT NULL AUTO_INCREMENT, username varchar(20) NOT NULL, password varchar(20) NOT NULL, PRIMARY KEY (id))"; if (mysql_query($sql)) {echo "[*]...................Creating New Table 'USERS' successfully";echo "

\n";} else {echo "[*]...................Error creating Table: " . mysql_error();echo "

\n";} //creating table emails $sql="CREATE TABLE security.emails ( id int(3)NOT NULL AUTO_INCREMENT, email_id varchar(30) NOT NULL, PRIMARY KEY (id) )"; if (mysql_query($sql)) {echo "[*]...................Creating New Table 'EMAILS' successfully"; echo "

\n";} else {echo "[*]...................Error creating Table: " . mysql_error();echo "

\n";} //creating table uagents $sql="CREATE TABLE security.uagents ( id int(3)NOT NULL AUTO_INCREMENT, uagent varchar(256) NOT NULL, ip_address varchar(35) NOT NULL, username varchar(20) NOT NULL, PRIMARY KEY (id) )"; if (mysql_query($sql)) {echo "[*]...................Creating New Table 'UAGENTS' successfully";echo "

\n";} else {echo "[*]...................Error creating Table: " . mysql_error();echo "

\n";} //creating table referers $sql="CREATE TABLE security.referers ( id int(3)NOT NULL AUTO_INCREMENT, referer varchar(256) NOT NULL, ip_address varchar(35) NOT NULL, PRIMARY KEY (id) )"; if (mysql_query($sql)) {echo "[*]...................Creating New Table 'REFERERS' successfully";echo "

\n";} else {echo "[*]...................Error creating Table: " . mysql_error();echo "

\n";} //inserting data $sql="INSERT INTO security.users (id, username, password) VALUES ('1', 'Dumb', 'Dumb'), ('2', 'Angelina', 'I-kill-you'), ('3', 'Dummy', 'p@ssword'), ('4', 'secure', 'crappy'), ('5', 'stupid', 'stupidity'), ('6', 'superman', 'genious'), ('7', 'batman', 'mob!le'), ('8', 'admin', 'admin'), ('9', 'admin1', 'admin1'), ('10', 'admin2', 'admin2'), ('11', 'admin3', 'admin3'), ('12', 'dhakkan', 'dumbo'), ('14', 'admin4', 'admin4')"; if (mysql_query($sql)) {echo "[*]...................Inserted data correctly into table 'USERS'";echo "

\n";} else {echo "[*]...................Error inserting data: " . mysql_error();echo "

\n";} //inserting data $sql="INSERT INTO `security`.`emails` (id, email_id) VALUES ('1', 'Dumb@dhakkan.com'), ('2', 'Angel@iloveu.com'), ('3', 'Dummy@dhakkan.local'), ('4', 'secure@dhakkan.local'), ('5', 'stupid@dhakkan.local'), ('6', 'superman@dhakkan.local'), ('7', 'batman@dhakkan.local'), ('8', 'admin@dhakkan.com')"; if (mysql_query($sql)) {echo "[*]...................Inserted data correctly into table 'EMAILS'";echo "

\n";} else {echo "[*]...................Error inserting data: " . mysql_error();echo "

\n";} //CREATE TABLE security.search (id int(3) NOT NULL AUTO_INCREMENT, search varchar(20) NOT NULL, PRIMARY KEY (id)); //INSERT INTO `security`.`search` (search) VALUES ( 'Dumb@dhakkan.com'), ('Angel@iloveu.com'), ('Dummy@dhakkan.local'), ( 'secure@dhakkan.local'), ( 'stupid@dhakkan.local'), ( 'superman@dhakkan.local'), ( 'batman@dhakkan.local'), ( 'admin@dhakkan.com')"; //including the Challenges DB creation file. include("../sql-connections/setup-db-challenge.php"); ?>

**Comment by HanwGeek** [comment]
I encountered with the same problem on Ubuntu16.04+php5.6.
And I guess it's about system code format. With the command 'locale', my format is **UTF-8**.

**Comment by parteeksingh005** [comment]
SETTING UP THE DATABASE SCHEMA AND POPULATING DATA IN TABLES:
Fatal error: Uncaught Error: Call to undefined function mysql_connect() in C:\xampp\htdocs\sqli1\sql-connections\setup-db.php:29 Stack trace: #0 {main} thrown in C:\xampp\htdocs\sqli1\sql-connections\setup-db.php on line 29

unable to setup datbase in XAMMP gettinh this error someone help me with this issue .

**Comment by ankitb458** [comment]
SETTING UP THE DATABASE SCHEMA AND POPULATING DATA IN TABLES:
Fatal error: Uncaught Error: Call to undefined function mysql_connect() in C:\xampp\htdocs\sqli1\sql-connections\setup-db.php:29 Stack trace: #0 {main} thrown in C:\xampp\htdocs\sqli1\sql-connections\setup-db.php on line 29

unable to setup datbase in XAMMP gettinh this error someone help me with this issue .

**Comment by ArrowShot** [comment]
> SETTING UP THE DATABASE SCHEMA AND POPULATING DATA IN TABLES:
> Fatal error: Uncaught Error: Call to undefined function mysql_connect() in C:\xampp\htdocs\sqli1\sql-connections\setup-db.php:29 Stack trace: #0 {main} thrown in C:\xampp\htdocs\sqli1\sql-connections\setup-db.php on line 29
> 
> unable to setup datbase in XAMMP gettinh this error someone help me with this issue .

are  u find solution

**Comment by Toum1n** [comment]
> ```
>                                           Welcome    Dhakkan
> ```
> 
> /var/www/sqli-labs/

I have solved the problem. I encountered this issue when using a Windows 10 virtual machine. Apache did not use PHP correctly to load this file, resulting in the. php file being displayed as plain text
